import mongoose from 'mongoose';
import { RefreshTokenSchema } from './refresh-token.schema';

describe('RefreshTokenSchema', () => {
  it('accepts UUID string ids generated by the login handler', () => {
    const RefreshTokenModel = mongoose.model(
      `RefreshTokenDocument_${Date.now()}`,
      RefreshTokenSchema,
    );

    const doc = new RefreshTokenModel({
      _id: '59d12ede-ee7f-43fa-bcef-07dab7e2b11f',
      token_hash: 'token-hash',
      user_id: 'user-id',
      family_id: 'family-id',
      is_used: false,
      is_revoked: false,
      expires_at: new Date('2026-08-01T00:00:00.000Z'),
    });

    expect(doc.validateSync()).toBeUndefined();
  });
});
